# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto/engine.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto
import grpclib


@dataclass
class AlarmRecord(betterproto.Message):
    """
    ── Request
    ────────────────────────────────────────────────────────────────────
    """

    _source_id: str = betterproto.string_field(1)
    managed_objects: str = betterproto.string_field(2)
    alarm_type: str = betterproto.string_field(3)
    probable_cause: str = betterproto.string_field(4)
    perceived_severity: str = betterproto.string_field(5)
    state: str = betterproto.string_field(6)
    created_at: str = betterproto.string_field(7)
    closed_at: str = betterproto.string_field(8)


@dataclass
class AnalyzeOnlineAlarmClusterRequest(betterproto.Message):
    request_id: str = betterproto.string_field(1)
    system: str = betterproto.string_field(2)
    alarm_records: List["AlarmRecord"] = betterproto.message_field(3)


@dataclass
class OnlineAlarmClusterResult(betterproto.Message):
    """
    ── Response
    ───────────────────────────────────────────────────────────────────
    """

    _source_id: str = betterproto.string_field(1)
    cluster_id: int = betterproto.int32_field(2)
    confidence: float = betterproto.float_field(3)


@dataclass
class OnlineAlarmClusterReport(betterproto.Message):
    request_id: str = betterproto.string_field(1)
    report_type: str = betterproto.string_field(2)
    status: str = betterproto.string_field(3)
    message: str = betterproto.string_field(4)
    results: List["OnlineAlarmClusterResult"] = betterproto.message_field(5)


class AlarmClusteringServiceStub(betterproto.ServiceStub):
    """
    ── Service
    ────────────────────────────────────────────────────────────────────
    """

    async def analyze_online_alarm_cluster(
        self,
        *,
        request_id: str = "",
        system: str = "",
        alarm_records: List["AlarmRecord"] = [],
    ) -> OnlineAlarmClusterReport:
        request = AnalyzeOnlineAlarmClusterRequest()
        request.request_id = request_id
        request.system = system
        if alarm_records is not None:
            request.alarm_records = alarm_records

        return await self._unary_unary(
            "/engine.AlarmClusteringService/AnalyzeOnlineAlarmCluster",
            request,
            OnlineAlarmClusterReport,
        )
